# 服务端口号
server:
  port: 8850
spring:
  application:
    # 服务应用名
    name: kafka-consumer
  # kafka配置
  kafka:
    # 配置连接到服务端集群的配置项 配置格式：host1:port1,host2:port2,...
    bootstrap-servers: localhost:9092
    # 消息消费者
    consumer:
      group-id: consumer-group
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer